export type Animations = {
	walk: string,
	idle: string,
	jumpscare: string,
	run: string?,
}

export type MorphData = {
	animations: Animations,
	displayName: string,
}

local Morphs: { [string]: MorphData } = {
	["HungryWormDaddy"] = {
		animations = {
			
			run = "rbxassetid://107989195745842",
			idle = "rbxassetid://98781033980114",
			jumpscare = "rbxassetid://96137844701964",
		},
		displayName = "Hungry Worm Daddy",
	},
	["HungryWormDoey"] = {
		animations = {
			
			run = "rbxassetid://107989195745842",
			idle = "rbxassetid://98781033980114",
			jumpscare = "rbxassetid://96137844701964",
		},
		displayName = "Hungry Worm Doey",
	},
	["HungryWormHamoodHabibi"] = {
		animations = {
			
			run = "rbxassetid://107989195745842",
			idle = "rbxassetid://98781033980114",
			jumpscare = "rbxassetid://96137844701964",
		},
		displayName = "Hungry Worm Hamood Habibi",
	},
	["HungryWormCatNap"] = {
		animations = {
			
			run = "rbxassetid://107989195745842",
			idle = "rbxassetid://98781033980114",
			jumpscare = "rbxassetid://96137844701964",
		},
		displayName = "Hungry Worm Cat Nap",
	},
	["HungryWormDogDay"] = {
		animations = {
			
			run = "rbxassetid://107989195745842",
			idle = "rbxassetid://98781033980114",
			jumpscare = "rbxassetid://96137844701964",
		},
		displayName = "Hungry Worm Dog Day",
	},
	["HungryWormHuggy"] = {
		animations = {
			
			run = "rbxassetid://107989195745842",
			idle = "rbxassetid://98781033980114",
			jumpscare = "rbxassetid://96137844701964",
		},
		displayName = "Hungry Worm Huggy",
	},
	["HungryWormSmiley"] = {
		animations = {
			
			run = "rbxassetid://107989195745842",
			idle = "rbxassetid://98781033980114",
			jumpscare = "rbxassetid://96137844701964",
		},
		displayName = "Hungry Worm Smiley",
	},
	["HungryWormMommy"] = {
		animations = {
			
			run = "rbxassetid://107989195745842",
			idle = "rbxassetid://98781033980114",
			jumpscare = "rbxassetid://96137844701964",
		},
		displayName = "Hungry Worm Mommy",
	},
	["HungryWormPhase2"] = {
		animations = {
			
			run = "rbxassetid://107989195745842",
			idle = "rbxassetid://98781033980114",
			jumpscare = "rbxassetid://96137844701964",
		},
		displayName = "Hungry Worm Phase 2",
	},
	["HungryWormPhase3"] = {
		animations = {
			
			run = "rbxassetid://107989195745842",
			idle = "rbxassetid://98781033980114",
			jumpscare = "rbxassetid://96137844701964",
		},
		displayName = "Hungry Worm Phase 3",
	},
	["HungryWorm"] = {
		animations = {
			idle = "rbxassetid://99840449575812",
			jumpscare = "rbxassetid://125753152004331",
			run = "rbxassetid://108789971402451",
		},
		displayName = "Hungry Worm",
	},
	["HungryWormCat"] = {
		animations = {
			idle = "rbxassetid://108508003683938",
			jumpscare = "rbxassetid://91715548494031",
			run = "rbxassetid://71151334318559",
		},
		displayName = "Hungry Worm Cat",
	},
	["HungryWormCatV2"] = {
		animations = {
			idle = "rbxassetid://128584606912953",
			jumpscare = "rbxassetid://138013083967655",
			run = "rbxassetid://78619735950315",
		},
		displayName = "Hungry Worm Cat V2",
	},
	["HungryWormGolden"] = {
		animations = {
			idle = "rbxassetid://99840449575812",
			jumpscare = "rbxassetid://125753152004331",
			run = "rbxassetid://108789971402451",
		},
		displayName = "Hungry Worm Golden",
	},
	["HungryWormPhase4"] = {
		animations = {
			idle = "rbxassetid://99840449575812",
			jumpscare = "rbxassetid://125753152004331",
			run = "rbxassetid://108789971402451",
		},
		displayName = "Hungry Worm Phase 4",
	},
	["HungryWormPibble"] = {
		animations = {
			idle = "rbxassetid://108508003683938",
			jumpscare = "rbxassetid://91715548494031",
			run = "rbxassetid://71151334318559",
		},
		displayName = "Hungry Worm Pibble",
	},
	["HungryWormSnake"] = {
		animations = {
			idle = "rbxassetid://128584606912953",
			jumpscare = "rbxassetid://75669641634534",
			run = "rbxassetid://78619735950315",
		},
		displayName = "Hungry Worm Snake",
	},
	["HungryWormSnakeDaddy"] = {
		animations = {
			idle = "rbxassetid://128584606912953",
			jumpscare = "rbxassetid://75669641634534",
			run = "rbxassetid://78619735950315",
		},
		displayName = "Hungry Worm Snake Daddy",
	},
	["HungryWormSnakeMommy"] = {
		animations = {
			idle = "rbxassetid://128584606912953",
			jumpscare = "rbxassetid://75669641634534",
			run = "rbxassetid://78619735950315",
		},
		displayName = "Hungry Worm Snake Mommy",
	},
	["HungryWormSnakePhase2"] = {
		animations = {
			idle = "rbxassetid://128584606912953",
			jumpscare = "rbxassetid://75669641634534",
			run = "rbxassetid://78619735950315",
		},
		displayName = "Hungry Worm Snake Phase 2",
	},
	["HungryWormSnakePhase3"] = {
		animations = {
			idle = "rbxassetid://128584606912953",
			jumpscare = "rbxassetid://75669641634534",
			run = "rbxassetid://78619735950315",
		},
		displayName = "Hungry Worm Snake Phase 3",
	},
	["HungryWormSonic"] = {
		animations = {
			idle = "rbxassetid://104158264572710",
			jumpscare = "rbxassetid://129741562150981",
			run = "rbxassetid://123090582958115",
		},
		displayName = "Hungry Worm Sonic",
	},
	["HungryWormTomato"] = {
		animations = {
			idle = "rbxassetid://99840449575812",
			jumpscare = "rbxassetid://76779218633223",
			run = "rbxassetid://108789971402451",
		},
		displayName = "Hungry Worm Tomato",
	},
}

return Morphs :: { [string]: MorphData }
